### ISSUE TITLE
Support replacing the base codestrat

### ISSUE THREAD

**Issue by vsevel** [quarkusio/code.quarkus.io#1491]
**Description**

to customize application creation, we created our own codestart.
see this [zulip discussion](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/custom.20create.20app.20scaffolding) for context.
when we are using the CLI, we can specify it with `-Dquarkus-base-codestart-artifact=...`.
but when we are using `code.quarkus.io` , we have to replace the original jar with ours.
right now we build our artifact, rename it to `io.quarkus.quarkus-devtools-base-codestarts-3.13.2.jar` , and replace it in our kubernetes deployment:
```
          image: 'quarkus/code-quarkus-app:latest'
          workingDir: /app
...
          volumeMounts:
            - name: code-quarkus-app-io-quarkus-quarkus-devtools-base-code-db97cd96
              mountPath: /deployments/lib/main/io.quarkus.quarkus-devtools-base-codestarts-3.13.2.jar
              subPath: io.quarkus.quarkus-devtools-base-codestarts-3.13.2.jar
...
      volumes:
        - name: code-quarkus-app-io-quarkus-quarkus-devtools-base-code-db97cd96
          configMap:
            name: code-quarkus-app-apps-config-cm
            items:
              - key: io.quarkus.quarkus-devtools-base-codestarts-3.13.2.jar-bdec193d
                path: io.quarkus.quarkus-devtools-base-codestarts-3.13.2.jar
            defaultMode: 420
```

this is a fragile solution. if there was a sha on the deployment to make it immutable, this would break it. and are lucky this is a jvm image. if this was native, there would be no way to change this.
I was hoping there would be a way to add our codestart without tricking the container.
in the end, since we are only overriding a few templates, it would have been nice to have an option to refer to a directory or a zip where we put the changed resources only, and the `code app` would just pick it up.

cc @ia3andy @aloubyansky
